# Generated by Django 3.1.7 on 2021-03-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_customer', models.IntegerField()),
                ('customer_denied', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_limit', models.IntegerField()),
                ('no_of_waiting', models.IntegerField()),
                ('no_of_counter', models.IntegerField()),
                ('count_free', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PriceCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_counter', models.IntegerField()),
                ('count_free', models.IntegerField()),
            ],
        ),
    ]
